---
version: '3'

vars:
  VAULT_PATH: ./inventory/group_vars/all.yaml
  VER: '2.5'
  PORT: 8000
  IMAGE: nicholaswilde/mkdocs-material
tasks:
  deps:
    desc: Install dependencies
    preconditions:
      - test -f requirements.yaml
    cmds:
      - sudo apt install -y pipx && pipx ensurepath
      - pipx upgrade-all
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml

  docs-deps:
    desc: Install mkdocs-material and pymdown-extensions
    cmds:
      - pipx uninstall mkdocs || true
      - pipx uninstall mkdocs-material || true
      - pipx uninstall pymdown-extensions || true
      - pipx install mkdocs
      - pipx install mkdocs-material
      - pipx install pymdown-extensions

  docs-deploy:
    desc: Deploy docs to GitHub Pages
    cmds:
      - pipx run --spec mkdocs mkdocs gh-deploy --force

  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 {{ .IMAGE }} serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
  list:
    desc: List all
    cmds:
      - ansible-inventory -i ./inventory/ --vars --list -y
  ping:
    desc: Ping all of inventory
    cmds:
      - ansible -i inventory/ all -m ping
  amd64-test:
    desc: Test amd64
    cmds:
      - ansible proxmox_all_lxc -i inventory/amd64.proxmox.yaml -m ansible.builtin.apt -a "update_cache=true" -b
  arm64-test:
    desc: Test arm64
    cmds:
      - ansible proxmox_all_lxc -i inventory/arm64.proxmox.yaml -m ansible.builtin.apt -a "update_cache=true" -b
  rpis-test:
    desc: Test arm64
    cmds:
      - ansible rpis -i inventory/02-rpi.yaml -m ansible.builtin.apt -a "update_cache=true" -b
  decrypt:
    desc: Decrypt
    preconditions:
      - test -f .vault_pass.enc
    cmds:
      - sops -d .vault_pass.enc > .vault_pass
      - chmod 600 .vault_pass
  encrypt:
    desc: Encrypt
    preconditions:
      - test -f .vault_pass
    cmds:
      - sops -e .vault_pass > .vault_pass.enc
  gpro:
    desc: Run gemini with gemini-2.5-pro model
    cmds:
      - gemini -m gemini-{{ .VER }}-pro
  gflash:
    desc: Run gemini with flash model
    cmds:
      - gemini -m gemini-{{ .VER }}-flash
  glite:
    desc: Run gemini with lite model
    cmds:
      - gemini -m gemini-{{ .VER }}-lite
  amd64-list:
    desc: List the amd64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/amd64.proxmox.yaml --list -y
  arm64-list:
    desc: List the arm64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/arm64.proxmox.yaml --list -y
  amd64-graph:
    desc: Graph the amd64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/amd64.proxmox.yaml --graph
  arm64-graph:
    desc: Graph the arm64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/arm64.proxmox.yaml --graph
  bootstrap:
    desc: Bootstrap the environment
    cmds:
      - task: deps
  deps:
    desc: Install dependencies
    preconditions:
      - test -f requirements.yaml
    cmds:
      - sudo apt install -y pipx && pipx install --include-deps ansible
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml
  setup:
    desc: Setup LXCs
    cmds:
      - ansible-playbook playbooks/setup_lxc.yaml
  update:
    desc: Update LXCs
    cmds:
      - ansible-playbook playbooks/update_lxc.yaml
  ve:
    desc: Edit vault
    cmds:
      - ansible-vault edit {{ .VAULT_PATH }}
  init:
    desc: Generate a new .vault_pass file
    preconditions:
      - sh: test ! -f .vault_pass.enc
        msg: ".vault_pass.enc already exists! Refusing to overwrite."
      - sh: test ! -f .vault_pass
        msg: ".vault_pass already exists! Refusing to overwrite."
    cmds:
      - openssl rand -hex 64 > .vault_pass
      - chmod 600 .vault_pass
  default:
    cmds:
      - task -l
    silent: true
