---
version: '3'

vars:
  VAULT_PATH: ./inventory/group_vars/all.yaml

tasks:
  bootstrap:
    desc: Bootstrap the environment
    cmds:
      - task: deps
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt install -y pipx && pipx install --include-deps ansible
      - ansible-galaxy role install -r requirements.yaml
  setup:
    desc: Setup LXCs
    cmds:
      - ansible-playbook playbooks/setup_lxc.yaml
  update:
    desc: Update LXCs
    cmds:
      - ansible-playbook playbooks/update_lxc.yaml
  ve:
    desc: Edit vault
    cmds:
      - ansible-vault edit {{ .VAULT_PATH }}
  default:
    cmds:
      - task -l
    silent: true
