---
version: '3'

vars:
  VAULT_PATH: ./inventory/group_vars/all.yaml
  VER: '2.5'

tasks:
  decrypt:
    desc: Decrypt
    preconditions:
      - test -f .vault_pass.enc
    cmds:
      - sops -d .vault_pass.enc > .vault_pass
      - chmod 600 .vault_pass
  encrypt:
    desc: Encrypt
    preconditions:
      - test -f .vault_pass
    cmds:
      - sops -e .vault_pass > .vault_pass.enc
  gpro:
    desc: Run gemini with gemini-2.5-pro model
    cmds:
      - gemini -m gemini-{{ .VER }}-pro
  gflash:
    desc: Run gemini with flash model
    cmds:
      - gemini -m gemini-{{ .VER }}-flash
  glite:
    desc: Run gemini with lite model
    cmds:
      - gemini -m gemini-{{ .VER }}-lite
  amd64-list:
    desc: List the amd64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/amd64.proxmox.yaml --list
  arm64-list:
    desc: List the arm64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/arm64.proxmox.yaml --list
  amd64-graph:
    desc: Graph the amd64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/amd64.proxmox.yaml --graph
  arm64-graph:
    desc: Graph the arm64 Proxmox inventory
    cmds:
      - ansible-inventory -i inventory/arm64.proxmox.yaml --graph
  bootstrap:
    desc: Bootstrap the environment
    cmds:
      - task: deps
  deps:
    desc: Install dependencies
    preconditions:
      - test -f requirements.yaml
    cmds:
      - sudo apt install -y pipx && pipx install --include-deps ansible
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml
  setup:
    desc: Setup LXCs
    cmds:
      - ansible-playbook playbooks/setup_lxc.yaml
  update:
    desc: Update LXCs
    cmds:
      - ansible-playbook playbooks/update_lxc.yaml
  ve:
    desc: Edit vault
    cmds:
      - ansible-vault edit {{ .VAULT_PATH }}
  default:
    cmds:
      - task -l
    silent: true
