---
pves:
  vars:
    ansible_user: root
  hosts:
    pve01:
      ansible_host: 192.168.2.128
    pve02:
      ansible_host: 192.168.2.192
    pve03:
      ansible_host: 192.168.2.198
    pve04:
      ansible_host: 192.168.2.67
