# inventory.docker.yml
all:
  hosts:
    # Use the *exact* name you gave your container with `docker run --name`
    ansible-test-target:
      ansible_connection: docker
      # Specify the Python interpreter path inside the container if it's non-standard
      # Usually '/usr/bin/python3' for modern Linux, but adjust if needed.
      ansible_python_interpreter: /usr/bin/python3
      # If your container runs as a non-root user by default and you need root:
      # ansible_user: your_container_user # The user Ansible connects as initially
      # ansible_become: yes              # To elevate privileges (requires sudo in container)
      # ansible_become_user: root
