---

- name: Get user variables
  ansible.builtin.user:
    name: root
    state: present
  register: user

- name: Setup micro
  ansible.builtin.include_tasks: micro.yaml

- name: Setup tmux
  ansible.builtin.include_tasks: tmux.yaml
