---
- name: Setup apt-cacher-ng source
  copy:
    src: 00aptproxy
    dest: "/etc/apt/apt.conf.d/00aptproxy"

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - git
      - gpg
      - autofs
      - pipx
      - ipcalc
      - net-tools
      - micro
      - qemu-guest-agent
      - gh
      - screen
      - dnsutils
    state: latest
    update_cache: true
