---
- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: root
    state: present
    key: https://github.com/nicholaswilde.keys

- name: Ensure private key is present
  ansible.builtin.copy:
    src: /home/nicholas/.ssh/id_rsa
    dest: "/root/.ssh/id_rsa"
    mode: "0600"
    owner: root
    group: root
