---
- name: Run a single task on all LXC containers
  hosts:
    - lxcAll
  become: true

  roles:
    - role: single
      when: "'docker' in hostvars[inventory_hostname]['tags']"
      ignore_errors: true
